#!/bin/bash
  
set -e

incdir=$(dirname $0)/..

restore_configs

. $incdir/base-zenxy-config

opt_set MOTHERBOARD "BOARD_MINIRAMBO"
opt_set PWM_MOTOR_CURRENT "{ 750, 750, 750 }"
opt_set DEFAULT_AXIS_STEPS_PER_UNIT "{ 100, 100, 400, 200 }"
