#!/bin/bash

set -e

incdir=$(dirname $0)/..

restore_configs
opt_enable SHOW_CUSTOM_BOOTSCREEN

. $incdir/base-cnc-config
. $incdir/board-archim1
. $incdir/no-dual-endstops
. $incdir/drv8825

opt_set MINIMUM_STEPPER_PULSE "2"

# Why?
opt_set DEFAULT_MAX_FEEDRATE "{ 120, 120, 30, 25 }"
opt_set Z3_DRIVER_TYPE "DRV8825"
opt_set E3_DRIVER_TYPE "DRV8825"
opt_set E4_DRIVER_TYPE "DRV8825"
opt_set E5_DRIVER_TYPE "DRV8825"
opt_disable SHOW_CUSTOM_BOOTSCREEN CUSTOM_USER_MENUS
opt_disable Z3_DRIVER_TYPE E3_DRIVER_TYPE E4_DRIVER_TYPE E5_DRIVER_TYPE 
