#!/bin/bash

set -e

restore_configs

$CFGDIR/common/v1-base-config
$CFGDIR/common/3dp-config
$CFGDIR/boards/mini-rambo
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/no-dual-endstops
$CFGDIR/accessories/aero-extruder

export PLATFORMIO_ENV=rambo
