#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}P

$CFGDIR/common/v1-base-config
$CFGDIR/common/3dp-config
$CFGDIR/boards/skr_pro
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/aero-extruder
$CFGDIR/accessories/auto-filament-change

opt_set X_DRIVER_TYPE  "TMC2209"
opt_set Y_DRIVER_TYPE  "TMC2209"
opt_set Z_DRIVER_TYPE  "TMC2209"
opt_set E0_DRIVER_TYPE  "TMC2209"

export PLATFORMIO_ENV=BIGTREE_SKR_PRO
