#!/bin/bash

set -e

restore_configs

$CFGDIR/common/v1-base-config
$CFGDIR/common/3dp-config
$CFGDIR/boards/ramps
$CFGDIR/accessories/drv8825
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/mk8-extruder
$CFGDIR/accessories/auto-filament-change

export PLATFORMIO_ENV=mega2560
