#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}DL

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_1p3
$CFGDIR/accessories/dummy-extruder
$CFGDIR/accessories/drv8825
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/dual-drivers-on-yz
$CFGDIR/boards/skr_1p3_dual

export PLATFORMIO_ENV=LPC1768
