#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}D

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/ramps
$CFGDIR/accessories/drv8825
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/dual-drivers-on-xy

opt_set DEFAULT_AXIS_STEPS_PER_UNIT "{ 200, 200, 800 }"

export PLATFORMIO_ENV=mega2560
