#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}DL

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/rambo
$CFGDIR/boards/rambo_dual
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/dual-drivers-on-yz
$CFGDIR/accessories/laser

opt_enable \
    Y2_DRIVER_TYPE \
    Z2_DRIVER_TYPE

opt_disable \
    E0_DRIVER_TYPE

export PLATFORMIO_ENV=rambo
