#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}S

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/archim2
$CFGDIR/accessories/tmc2130
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/no-dual-endstops

opt_set X_DRIVER_TYPE "TMC2130"
opt_set Y_DRIVER_TYPE "TMC2130"
opt_set Z_DRIVER_TYPE "TMC2130"

export PLATFORMIO_ENV=DUE_archim
