#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}DL

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_turbo_1p4
$CFGDIR/accessories/dummy-extruder
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/dual-drivers-on-yz
$CFGDIR/boards/skr_turbo_1p4_dual

opt_set Y2_DRIVER_TYPE "TMC2209"
opt_set Z2_DRIVER_TYPE "TMC2209"

export PLATFORMIO_ENV=LPC1769