#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}D

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_1p3
$CFGDIR/accessories/dummy-extruder
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/no-dual-endstops

# For some weird reason TMC2209 directions are reversed on SKR1.3 boards
opt_set INVERT_X_DIR true
opt_set INVERT_Y_DIR false
opt_set INVERT_Z_DIR true

export PLATFORMIO_ENV=LPC1768
