#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}D

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_pro
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/TFT35_e3_v3_CNC
$CFGDIR/accessories/dual-drivers-on-xy
$CFGDIR/boards/skr_pro_dual


opt_set X_DRIVER_TYPE  "TMC2209"
opt_set Y_DRIVER_TYPE  "TMC2209"
opt_set Z_DRIVER_TYPE  "TMC2209"
opt_set X2_DRIVER_TYPE  "TMC2209"
opt_set Y2_DRIVER_TYPE  "TMC2209"

opt_set X2_CURRENT 900
opt_set Y2_CURRENT 900

opt_disable \
    E0_DRIVER_TYPE

export PLATFORMIO_ENV=BIGTREE_SKR_PRO
