#!/bin/bash

set -e

restore_configs

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/rambo
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/no-dual-endstops
$CFGDIR/accessories/laser-32bit

export PLATFORMIO_ENV=rambo
