#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}DL

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/ramps
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/dual-drivers-on-yz
$CFGDIR/boards/ramps_dual
$CFGDIR/accessories/laser

opt_set X_DRIVER_TYPE "DRV8825"
opt_set Y_DRIVER_TYPE "DRV8825"
opt_set Z_DRIVER_TYPE "DRV8825"
opt_set Y2_DRIVER_TYPE "DRV8825"
opt_set Z2_DRIVER_TYPE "DRV8825"

export PLATFORMIO_ENV=mega2560
