#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}DL

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_pro
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/TFT35_e3_v3_CNC
$CFGDIR/accessories/dual-drivers-on-yz
$CFGDIR/boards/skr_pro_dual
$CFGDIR/accessories/laser

opt_set SPINDLE_LASER_PWM_PIN PC9
opt_set SPINDLE_LASER_ENA_PIN PB0 # Heater2


opt_set X_DRIVER_TYPE  "TMC2209"
opt_set Y_DRIVER_TYPE  "TMC2209"
opt_set Z_DRIVER_TYPE  "TMC2209"
opt_set Y2_DRIVER_TYPE  "TMC2209"
opt_set Z2_DRIVER_TYPE  "TMC2209"

opt_set Y2_CURRENT 900
opt_set Z2_CURRENT 900

opt_disable \
    E0_DRIVER_TYPE


if [ ${MARLIN_CONFIG_VERSION} -gt 02010205 ]; then
  export PLATFORMIO_ENV=BTT_SKR_PRO
  echo "Marlin > 2.1.2.5"
else
  export PLATFORMIO_ENV=BIGTREE_SKR_PRO
  echo "Marlin <= 2.1.2.5"
fi
