#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}S

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_pro
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/TFT35_e3_v3_CNC
$CFGDIR/accessories/no-dual-endstops
$CFGDIR/accessories/laser

opt_add SPINDLE_LASER_PWM_PIN PC9
opt_add SPINDLE_LASER_ENA_PIN PB0 // Heater2

opt_set X_DRIVER_TYPE  "TMC2209"
opt_set Y_DRIVER_TYPE  "TMC2209"
opt_set Z_DRIVER_TYPE  "TMC2209"

export PLATFORMIO_ENV=BIGTREE_SKR_PRO
