#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}S

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_1p3
$CFGDIR/accessories/dummy-extruder
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/dual-drivers-on-yz
$CFGDIR/accessories/invert-all-axes # TMC2209 directions are reversed on SKR1.3 boards
$CFGDIR/accessories/sensorless-homing

export PLATFORMIO_ENV=LPC1768
