#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}Z

$CFGDIR/common/v1-base-config
$CFGDIR/common/zenxy-config
$CFGDIR/boards/skr_pro
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/no-dual-endstops

opt_set X_DRIVER_TYPE  "TMC2209"
opt_set Y_DRIVER_TYPE  "TMC2209"
opt_set Z_DRIVER_TYPE  "TMC2209"
opt_set E0_DRIVER_TYPE  "TMC2209"

if [ ${MARLIN_CONFIG_VERSION} -gt 02010205 ]; then
  export PLATFORMIO_ENV=BTT_SKR_PRO
  echo "Marlin > 2.1.2.5"
else
  export PLATFORMIO_ENV=BIGTREE_SKR_PRO
  echo "Marlin <= 2.1.2.5"
fi
