#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}Z

$CFGDIR/common/v1-base-config
$CFGDIR/common/zenxy-config
$CFGDIR/boards/ramps
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/no-dual-endstops

opt_set X_DRIVER_TYPE "DRV8825"
opt_set Y_DRIVER_TYPE "DRV8825"
opt_set Z_DRIVER_TYPE "DRV8825"


export PLATFORMIO_ENV=mega2560
