#!/bin/bash
  
incdir=$(dirname $0)/..

restore_configs

. $incdir/base-3dp-config
. $incdir/avr-lcd-timings 

opt_set MOTHERBOARD "BOARD_MINIRAMBO"
opt_set PWM_MOTOR_CURRENT "{ 750, 750, 950 }"
opt_set DEFAULT_AXIS_STEPS_PER_UNIT "{ 100, 100, 400, 837 }"
opt_set E0_AUTO_FAN_PIN "6"
