#!/bin/bash
  
incdir=$(dirname $0)/..

restore_configs

. $incdir/base-3dp-config
. $incdir/avr-lcd-timings 
. $incdir/drv8825

opt_set DEFAULT_AXIS_STEPS_PER_UNIT "{ 200, 200, 800, 200 }"
opt_enable REVERSE_ENCODER_DIRECTION

# Why?
opt_set TEMP_SENSOR_0 "11"

opt_set PWM_MOTOR_CURRENT "{ 800, 900, 950 }"
opt_disable PWM_MOTOR_CURRENT
