#!/bin/bash

set -e

incdir=$(dirname $0)/..

restore_configs
opt_enable SHOW_CUSTOM_BOOTSCREEN

. $incdir/base-cnc-config
. $incdir/board-archim1
. $incdir/dual-endstops
. $incdir/drv8825

opt_set MINIMUM_STEPPER_PULSE "3"

# Why?
opt_set DEFAULT_MAX_FEEDRATE "{ 120, 120, 30, 120 }"
opt_disable SHOW_CUSTOM_BOOTSCREEN CUSTOM_USER_MENUS SOFT_ENDSTOPS_MENU_ITEM MIN_SOFTWARE_ENDSTOPS \
    REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
