#!/bin/bash

set -e

incdir=$(dirname $0)/..

restore_configs
opt_enable SHOW_CUSTOM_BOOTSCREEN

. $incdir/base-cnc-config
. $incdir/no-dual-endstops
. $incdir/avr-lcd-timings

opt_set MOTHERBOARD "BOARD_MINIRAMBO"
opt_set DEFAULT_AXIS_STEPS_PER_UNIT "{ 100, 100, 400, 100 }"
opt_set PWM_MOTOR_CURRENT "{ 900, 900, 900 }"

# Why?
opt_set DIGIPOT_MOTOR_CURRENT "{ 95, 95, 95, 95, 95 }"
opt_disable DIGIPOT_MOTOR_CURRENT
