#!/bin/bash

set -e

incdir=$(dirname $0)/..

restore_configs
opt_enable SHOW_CUSTOM_BOOTSCREEN

. $incdir/base-cnc-config
. $incdir/board-rambo
. $incdir/no-dual-endstops

opt_enable REVERSE_ENCODER_DIRECTION
