#!/bin/bash

incdir=$(dirname $0)/..

use_example_configs CNC/MPCNC
opt_enable SHOW_CUSTOM_BOOTSCREEN

. $incdir/drv8825
. $incdir/avr-lcd-timings
. $incdir/no-dual-endstops

opt_set DEFAULT_AXIS_STEPS_PER_UNIT "{ 200, 200, 800, 200 }"
opt_enable REVERSE_ENCODER_DIRECTION
