#!/bin/bash

set -ex

. $(dirname "$0")/env

machine=$1
shift

[ "$machine" ] || exit 2

eval $($V1_ROOT/$CFGDIR/build-settings.py "$machine")

cd "$V1_ROOT/$MARLINDIR"
export PATH=$PATH:buildroot/bin

restore_configs

for f in config/examples/$machine/{Configuration.h,Configuration_adv.h,_Bootscreen.h,_Statusscreen.h}; do
  [ -f "$f" ] && cp "$f" Marlin/
done

platformio run --project-dir . -e "$env" --silent "$@"
