#!/bin/bash

SCRIPTDIR="v1-scripts/configs"
CONFIGDIR="config/examples"

set -e

PATH=$PATH:buildroot/bin
export PATH

for script in "$SCRIPTDIR"/{MPCNC,MP3DP,ZenXY}/*; do
    machine=${script#$SCRIPTDIR/}
    cfgdir=$CONFIGDIR/$machine

    echo "Generating config for $machine"
    $script
    
    mkdir -p "$cfgdir"
    cp Marlin/Configuration{.h,_adv.h} "$SCRIPTDIR"/_Bootscreen.h "$cfgdir"
done

restore_configs
