#!/bin/bash

ORIGIN_REMOTE_NAME="${ORIGIN_REMOTE_NAME:-origin}"
MIRROR_BRANCH="${MIRROR_BRANCH:-bugfix-2.0.x}"
MACHINES_BRANCH="${MACHINES_BRANCH:-HEAD}"
BUILD_BRANCH="${BUILD_BRANCH:-v1-$MIRROR_BRANCH}"
ADD_BRANCHES="${ADD_BRANCHES:-v1-base-config}"

set -xe

# Combine v1-machines and Marlin, this ensures v1-scripts are available for builds
# NB! we must detach the head here to make sure we don't destroy a local v1-machines branch
machines_ref=$(git rev-parse "$MACHINES_BRANCH")
git rebase $MIRROR_BRANCH $machines_ref

# Merge branches that are not yet ready to be submitted to upstream
for branch in $ADD_BRANCHES; do
    git fetch "$ORIGIN_REMOTE_NAME" "$branch"
    git merge --no-stat --no-ff --no-edit "$ORIGIN_REMOTE_NAME/$branch"
done

# Generate and commit configs
v1-scripts/generate-configs
git add config/examples
git commit -m 'Add configuratons for V1 machines'

# Helpful message to user when running locally
old_ref=$(git rev-parse --verify "$BUILD_BRANCH" 2> /dev/null) && \
    echo "Overwriting $BUILD_BRANCH branch. Use git checkout -b new-name $old_ref to get it back"

# Store results to local branch
git branch -f "$BUILD_BRANCH"
git branch -u "$ORIGIN_REMOTE_NAME/$BUILD_BRANCH" "$BUILD_BRANCH" || true # OK to fail
