#!/bin/bash

set -ex

cfg=$1
eval $(v1-scripts/configs/build-settings.py "$cfg")

flatname=$(echo "$cfg" | sed 's@/@_@g')
dirname="$flatname"

mkdir -p .bin
cp ".pio/build/$env/$out" ".bin/$flatname.$out"

mkdir -p .zip
ln -sf ".." ".zip/$dirname-src"
(cd ".zip" && zip -prq "$flatname-src.zip" "$dirname-src"/*)
