name: skr_turbo

on:
  schedule:
    # At 12:15 each day. No idea what time zone this is...
    - cron:  '15 12 * * *'
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    paths-ignore:
    - src/configs/V1*Archim*
    - src/configs/V1*Rambo*
    - src/configs/V1*Ramps*
    - src/configs/V1*Skr1p3*
    - '**/*.md'
  release:
    types:
      - published

jobs:
  build:

    env:
      MARLIN_VERSION: ${{ matrix.branch }}
      CONFIG_NAME: ${{ matrix.machine }}
      V1_VERSION: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

    name: ${{ matrix.machine }}-${{ matrix.branch }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Allow all machines to finish building
      matrix:
        branch: ${{ fromJson(
          github.event_name == 'schedule' && '["bugfix-2.1.x"]' ||
          github.event_name == 'pull_request' && '["bugfix-2.1.x", "2.1.2"]' ||
          '["2.1.2"]') }}
        machine:
        - V1CNC_SkrTurbo_8825
        - V1CNC_SkrTurbo_DualLR_8825
        - V1CNC_SkrTurbo_Dual_8825
        - V1CNC_SkrTurbo_2209
        - V1CNC_SkrTurbo_Dual_2209
        - V1CNC_SkrTurbo_DualLR_2209

    steps:

    # First, cancel unfinished jobs.
    #- uses: technote-space/auto-cancel-redundant-job@v1.7.5

    # Based on .github/workflows/test-builds.yml
    - name: Select Python 3.x
      uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/master.zip
        platformio update

    - name: Check out MarlinBuilder
      uses: actions/checkout@v4.2.2

    - name: Check out MarlinFirmware
      uses: actions/checkout@v4.2.2
      with:
        repository: MarlinFirmware/Marlin
        ref: ${{ matrix.branch }}
        path: Marlin
        clean: true
        fetch-depth: 1

    - name: Configure
      run: |
        src/core/config-for-machine ${{ matrix.machine }}

    - name: Zip up Marlin
      run: |
        src/core/zip-marlin

    - name: Upload src artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ matrix.machine }}-${{ matrix.branch }}
        path: |
          Marlin_*.zip

    - name: Build
      run: |
        src/core/build-for-machine

    - name: Zip up release
      run: |
        src/core/zip-release

    - name: Upload built artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ matrix.machine }}-${{ matrix.branch }}
        path: |
          firmware*
          Marlin_*.zip

    - name: Upload Marlin-${{ matrix.machine }}-${{ matrix.branch }}.zip to release
      if: ${{ github.event_name == 'release' }}
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: Marlin-Release.zip
        asset_name: ${{ matrix.machine }}-${{ matrix.branch }}.zip
        asset_content_type: application/zip